import Head from "next/head";
import styles from "../styles/Home.module.css";

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export default function Home({ data }) {
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Movies&apos; List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          List of <a>Movies</a>
        </h1>

        <p className={styles.description}>
          This project contains the basics usage of{" "}
          <code className={styles.code}>Next.js</code> and{" "}
          <code className={styles.code}>Prisma</code>{" "}
        </p>

        <div className={styles.grid}>
          {data.map((item) => (
            <a
              href="https://nextjs.org/docs"
              className={styles.card}
              key={item.id}
            >
              <h2>{item.title} &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/mhizta-mammut">
          Create with ❤️ by{" "}
          <span className={styles.authorName}> &nbsp;Hamisu Muhammad</span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const movies = await prisma.movie.findMany();

  const data = [
    {
      id: 1,
      title: "title",
    },
    {
      id: 2,
      title: "another title",
    },
  ];

  return {
    props: {
      data: movies,
    },
  };
}
