import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          List of <a>Movies</a>
        </h1>

        <p className={styles.description}>
          This project contains the basics usage of{" "}
          <code className={styles.code}>Next.js</code> and{" "}
          <code className={styles.code}>Prisma</code>{" "}
        </p>

        <ul className="">
          {data.map((item) => (
            <li key={item.id}>{item.title}</li>
          ))}
        </ul>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/mhizta-mammut">
          Create with ❤️ by{" "}
          <span className={styles.authorName}> &nbsp;Hamisu Muhammad</span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const data = [
    {
      id: 1,
      title: "title",
    },
    {
      id: 2,
      title: "another title",
    },
  ];

  return {
    props: {
      data,
    },
  };
}
